### ISSUE TITLE
Magic Item Crashes Game Upon Use

### ISSUE THREAD

**Issue by snydecor000** [randomtestfive/DerpCoin2#11]
Error log:
java.lang.NullPointerException: Rendering entity in world
    at net.minecraft.client.renderer.entity.RenderSnowball.func_76986_a(SourceFile:28)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1294)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by randomtestfive** [comment]
Checkout
http://www.minecraftforge.net/forum/index.php?topic=28219.0

**Comment by randomtestfive** [comment]
Change the line that adds the renderSnowball to have
RenderSnowball(Minecraft.getMinecraft().getRenderManager(), derpCoin, Minecraft.getMinecraft().getRenderItem())

**Comment by randomtestfive** [comment]
Change the null out with Minecraft.getMinecraft().getRenderItem()

**Comment by snydecor000** [comment]
this is what is was in the beginning:
new RenderSnowball(null, derpCoin, null)

so I changed it to this:
(Minecraft.getMinecraft().getRenderManager(), derpCoin, Minecraft.getMinecraft().getRenderItem())
and it still crashed the world

**Comment by randomtestfive** [comment]
You've rebuilt and put it in the mods folder right?

**Comment by snydecor000** [comment]
Yes, I have.  I just retried and got the same result

**Comment by snydecor000** [comment]
We are talking about the line in Thingy.java in the PreInit function, right?

**Comment by randomtestfive** [comment]
Appears that that line needs to be in commonproxy.java in the registerRenderers function.

**Comment by randomtestfive** [comment]
Nope just kidding

**Comment by randomtestfive** [comment]
New crash log file please

**Comment by snydecor000** [comment]
java.lang.NullPointerException: Rendering entity in world
    at net.minecraft.client.renderer.entity.RenderSnowball.func_76986_a(SourceFile:28)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1294)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1207)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1032)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
